### ISSUE TITLE
auth doesn't work with errors

### ISSUE THREAD

**Issue by ycao56** [ibm-cloud-solutions/hubot-ibmcloud-auth#6]
�[Thu Aug 04 2016 17:35:06 GMT+0000 (UTC)] ERROR audit.js: Error: Not Found, Adapter: slack, Robot: ibmcloudbot, Room: C183AAJRK, User: {"id":"U0C44F480","name":"jorge","real_name":"JORGE PADILLA"}
�[Thu Aug 04 2016 17:35:06 GMT+0000 (UTC)] ERROR audit.js: Error: Not Found, Adapter: slack, Robot: ibmcloudbot, Room: C183AAJRK, User: {"id":"U0C44F480","name":"jorge","real_name":"JORGE PADILLA"}

**Comment by ngawor** [comment]
Well, those are audit errors :).  But the reason auth doesn't work is that hubot-slack went up to 4.0, which pulled 3.4.1 of node-slack-sdk, which changed the location of email addresses in the user object.
